### ISSUE TITLE
Integração de Produtos

### ISSUE THREAD

**Issue by danilogubee** [maco-studios/gubee-integration#4]
### Produtos Simples/Variantes:

**Todos os testes abaixo foram executados em produtos do tipo simples e variante, e apresentaram o mesmo problema em ambos.**

- [ ] Ao executar o comando para integrar um novo produto na Gubee, é gerado um erro no Magento, porém o produto é integrado com sucesso.
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/af91aec3-f5ea-49f6-a546-378554028969)

- [ ] Ao alterar o estoque de um produto, é gerado um erro ao executar o comando.
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/541e274f-a87d-444b-a496-c560724f72b4)

- [ ] Ao definir o produto como fora de estoque ou em estoque no Magento, é gerado um comando na fila de envio de estoque, executado com sucesso, mas não é alterado nada na Gubee.
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/1bbde731-9365-4423-8e6a-628364a37f13)
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/f5392897-8af3-4ef9-9caa-4275461a426c)
Não foi gerado nenhum erro:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/d161b932-b945-4cfa-9fdd-fdfdc6428355)

### Produtos Variantes:

**Os erros encontrados abaixo foram apenas nos produtos variantes**

- [ ] Os atributos definidos no produto configurável não estão sendo enviados para a Gubee. Para esse teste, foi definido o atributo "atributoTeste". O mesmo teste foi realizado com este atributo nos produtos simples, e funcionou. O atributo foi adicionado no produto configurável do Magento:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/9b50493f-52fd-4f25-b67b-f9c92036930b)
Comando de envio do produto:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/950e5981-01b6-4feb-bcaf-2402bd8755a5)
Verificado o log de integração e nenhum erro foi encontrado:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/a0d740db-7df2-459b-b37b-29fbe3bf67df)
Produto na Gubee após o envio:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/f8845fba-19d5-4bea-91d4-6fb9d6e4eed8)

- [ ] A descrição dos produtos que estão vinculados a um configurável, não está sendo enviada para a Gubee. Foi definido apenas no produto configurável o atributo enviar para a Gubee como Sim.
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/0f4a4f03-2667-4be2-acd5-e9f357eae79f)
Produtos associados ao configurável que não atualizam a descrição:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/e8c110ac-d82f-4a71-9f79-19082e7a460e)
Comando de envio do produto executado:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/431bf613-653e-4574-8e63-e4d2f3700f0c)
Não encontrado nenhum erro no log de integração:
![image](https://github.com/maco-studios/gubee-integration/assets/165683575/0b567ea6-6ac6-4ccf-8057-378bb2df6d07)

**Comment by macoaure** [comment]
Boa tarde @danilogubee,

Foi aplicada uma correção no SDK  removendo a feature que injeta um objeto no retorno da criação na api.

Atualizando o SDK vc não terá mais este problema.
